default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME_DEVELOPMENT'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: <%= ENV['DATABASE_NAME_TEST'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  min_messages: warning

production:
  <<: *default
  database: <%= ENV['DB_NAME'].presence || 'snibox_production' %>
  username: <%= ENV['DB_USER'].presence || 'snibox' %>
  password: <%= ENV['DB_PASS'].presence || '' %>
  host: <%= ENV['DB_HOST'].presence || 'localhost' %>
  port: <%= ENV['DB_PORT'].presence || '5432' %>
